server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/master
          jwk-set-uri: http://keycloak:8080/realms/master/protocol/openid-connect/certs

management:
  metrics:
    tags:
      application: ${spring.application.name}