server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/auth/realms/master}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8080/auth/realms/master/protocol/openid-connect/certs}

management:
  metrics:
    tags:
      application: ${spring.application.name}