server:
  port: 8082

spring:
  application:
    name: auth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/eduflex

keycloak:
  realm: eduflex
  auth-server-url: http://keycloak:8080/
  resource: eduflex-29051870
  credentials:
    secret: qh0DFD9VjyXh5KHGbXZTNFMDYhE5xA98
    username: admin
    password: admin
  use-resource-role-mappings: true

management:
  metrics:
    tags:
      application: ${spring.application.name}